[package]
name = "parts"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
anyhow = "1.0.75"
serde = { version = "1.0.210", features = ["derive"] }
serde_yaml = "0.9.34"
csv = "1.3.0"
encoding_rs = "0.8.34"
